<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="simplifiedbpmn" nsURI="http://www.cpoubel.org/simplifiedbpmn"
    nsPrefix="simplifiedbpmn">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EEnum" name="GatewayDirection">
    <eLiterals name="Unspecified"/>
    <eLiterals name="Converging" value="1"/>
    <eLiterals name="Diverging" value="2"/>
    <eLiterals name="Mixed" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="IntermediateEventType">
    <eLiterals name="Message"/>
    <eLiterals name="Signal" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FlowElement" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="FlowElementContainer" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="onlyOneStartEvent"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="onlyOneStartEvent" value="&#xA;&#x9;&#x9;self.flowElements->select(e | e.oclIsTypeOf(StartEvent) )->size() = 1"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="flowElements" upperBound="-1"
        eType="#//FlowElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resource" lowerBound="1"
        eType="#//ResourceRole" eOpposite="#//ResourceRole/processes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Process" eSuperTypes="#//FlowElementContainer"/>
  <eClassifiers xsi:type="ecore:EClass" name="FlowNode" abstract="true" eSuperTypes="#//FlowElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incoming" upperBound="-1"
        eType="#//SequenceFlow" eOpposite="#//SequenceFlow/targetRef"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoing" upperBound="-1"
        eType="#//SequenceFlow" eOpposite="#//SequenceFlow/sourceRef"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SequenceFlow" eSuperTypes="#//FlowElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetRef" lowerBound="1"
        eType="#//FlowNode" eOpposite="#//FlowNode/incoming"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceRef" lowerBound="1"
        eType="#//FlowNode" eOpposite="#//FlowNode/outgoing"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Gateway" abstract="true" eSuperTypes="#//FlowNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gatewayDirection" lowerBound="1"
        eType="#//GatewayDirection"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ANDGateway" eSuperTypes="#//Gateway"/>
  <eClassifiers xsi:type="ecore:EClass" name="XORGateway" eSuperTypes="#//Gateway"/>
  <eClassifiers xsi:type="ecore:EClass" name="ORGateway" eSuperTypes="#//Gateway"/>
  <eClassifiers xsi:type="ecore:EClass" name="Activity" abstract="true" eSuperTypes="#//FlowNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="Task" eSuperTypes="#//Activity">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="oneIn oneOut"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="oneIn" value="self.incoming->size() = 1"/>
      <details key="oneOut" value="self.outgoing->size() = 1"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Event" abstract="true" eSuperTypes="#//FlowNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="CatchEvent" abstract="true" eSuperTypes="#//Event"/>
  <eClassifiers xsi:type="ecore:EClass" name="StartEvent" eSuperTypes="#//CatchEvent">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="noIncomingFlow"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="noIncomingFlow" value="self.incoming->size() = 0"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntermediateCatchEvent" eSuperTypes="#//CatchEvent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eventType" lowerBound="1"
        eType="#//IntermediateEventType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BoundaryEvent" eSuperTypes="#//CatchEvent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eventType" lowerBound="1"
        eType="#//IntermediateEventType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cancelActivity" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attachedToRef" lowerBound="1"
        eType="#//Activity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ThrowEvent" abstract="true" eSuperTypes="#//Event"/>
  <eClassifiers xsi:type="ecore:EClass" name="EndEvent" eSuperTypes="#//ThrowEvent">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="noOutgoingFlow"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="noOutgoingFlow" value="self.outgoing->size() = 0"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntermediateThrowEvent" eSuperTypes="#//ThrowEvent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eventType" lowerBound="1"
        eType="#//IntermediateEventType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceRole">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="processes" upperBound="-1"
        eType="#//FlowElementContainer" eOpposite="#//FlowElementContainer/resource"/>
  </eClassifiers>
</ecore:EPackage>
